- hosts: jenkins
  become: true
  roles:
    - bertvv.rh-base
    - geerlingguy.java
    - lean_delivery.jenkins
    - geerlingguy.pip
    - geerlingguy.docker
    - lean_delivery.sonarqube
    - diodonfrost.sonar_scanner
